{"name": "新增用户", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'json'", "trace": "self = <tc.test_userManage.TestUserManage object at 0x04758CD0>\ninData = '{\"password\":\"\",\"password_confirm\": \"88888888\",\"username\":\"001\"}'\nexp = '{\\'code\\':500,\\'msg\\':\"Key:\\'userAddRequest.password\\'Error:Field validation for \\'password\\' failed on the\\'required\\' tag\"}'\n\n    @allure.title(\"新增用户\")\n    @pytest.mark.parametrize(\"inData,exp\",get_excel_data(\"user\",2,6,7,8))\n    def test_add_user(self,inData,exp):\n        res = UserManage().add_user(self.token,inData)\n        print(inData)\n>       assert self.test.assert_code(res.json()[\"code\"],200)\nE       AttributeError: 'dict' object has no attribute 'json'\n\ntest_userManage.py:19: AttributeError"}, "attachments": [{"name": "log", "source": "5d8e5285-3c36-427a-9016-6613f52ca857-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "inData", "value": "'{\"password\":\"\",\"password_confirm\": \"88888888\",\"username\":\"001\"}'"}, {"name": "exp", "value": "'{'code':500,'msg':\"Key:'userAddRequest.password'Error:Field validation for 'password' failed on the'required' tag\"}'"}], "start": 1604654304314, "stop": 1604654304323, "uuid": "6131dee6-7670-46de-bcec-562af5567961", "historyId": "7eb54adce62304271e7e440620b1c341", "testCaseId": "f56f10c6b6679a14e1ccd1e8f399d334", "fullName": "test_userManage.TestUserManage#test_add_user", "labels": [{"name": "suite", "value": "test_userManage"}, {"name": "subSuite", "value": "TestUserManage"}, {"name": "host", "value": "dadaxPC008"}, {"name": "thread", "value": "13072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_userManage"}]}